/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ontopad.misc;

/**
 *
 * @author Amann
 */
public enum OWLdatatype {
   
 XSD_ANYURI,
 XSD_BASE64BINARY,
 XSD_BOOLEAN,
 XSD_BYTE,
 XSD_DATETIME,
 XSD_DATETIMESTAMP,
 XSD_DECIMAL,
 XSD_DOUBLE,
 XSD_FLOAT,
 XSD_HEXBINARY,
 XSD_INT,
 XSD_INTEGER,
 XSD_LANGUAGE,
 XSD_LONG,
 XSD_NAME,
 XSD_NCNAME,
 XSD_NEGATIVEINTEGER,
 XSD_NMTOKEN,
 XSD_NONNEGATIVEINTEGER,
 XSD_NONPOSITIVEINTEGER,
 XSD_NORMALIZEDSTRING,
 RDF_PLAINLITERAL,
 XSD_POSITIVEINTEGER,
 OWL_RATIONAL,
 OWL_REAL,
 XSD_SHORT,
 XSD_STRING,
 XSD_TOKEN,
 XSD_UNSIGNEDBYTE,
 XSD_UNSIGNEDINT,
 XSD_UNSIGNEDLONG,
 XSD_UNSIGNEDSHORT,
 RDF_XMLLITERAL;
}
